### ISSUE TITLE
Write Feedback

### ISSUE THREAD

**Issue by AnEb0711** [EnricSala/influxdb-matlab#12]
Hello,

I get the error code 400 Bad Request during my write process and I don't know why. With some samples it works and with some it doesn't. I found at the InfluxDB documentation, that it is possible to set pretty=true to enable pretty-print JSON. How does this work with your Matlab add on?

**Comment by EnricSala** [comment]
Hi @AnEb0711, sorry for the late reply.

> I get the error code 400 Bad Request during my write process and I don't know why.

Do you get a specific error message? You can also try executing the write command directly to help debug the issue further.

> I found at the InfluxDB documentation, that it is possible to set pretty=true to enable pretty-print JSON. How does this work with your Matlab add on?

That should not be relevant to the issue because write requests don't use JSON, they are formatted in [line protocol](https://docs.influxdata.com/influxdb/v1.8/write_protocols/line_protocol_tutorial/).

If you would like to see what the request looks like when writing to the DB, you can use the `.toLine()` method, for example:
```matlab
series1 = Series('weather') ...
    .tags('city', 'paris', 'country', 'france') ...
    .fields('temperature', 24.3, 'humidity', 70.4) ...
    .time(datetime('today', 'TimeZone', 'local'));

request = series1.toLine()
```

**Comment by AnEb0711** [comment]
Hey @EnricSala ,

thanks for your response. I think I found the error. I use a number as tag, now I have changed it with num2str() and it looks like, as it works. 

It was not a specific error message, only the general one, that it was the error during the write command.

**Comment by EnricSala** [comment]
I don't think number tag values are supported, see the docs:
https://docs.influxdata.com/influxdb/v1.8/concepts/glossary/#tag-value

Converting it to a string does make sense :+1: 

I'm closing this issue, feel free to reopen if necessary :)
